---
variables:
  LEKTOR_BUILD_FLAGS: scss
  SITE_URL: support.torproject.org
  STAGING_URL: support.staging.torproject.net
  TRANSLATION_BRANCH: support-portal

include:
  - project: tpo/tpa/ci-templates
    ref: lektor-marble
    file:
      - lektor.yml
      - static-shim-deploy.yml
